# Generated by Django 3.2 on 2023-07-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_sale_sale_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='no_img.png', upload_to='media/supplier_image'),
        ),
    ]
