# Generated by Django 3.2 on 2023-07-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
